apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-mongodb
  labels:
    app: python-guestbook
    tier: db
    monitoring: "enabled"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"  # Update to new metrics port
spec:
  ports:
    - name: http-server
      port: 27017
      targetPort: 27017
    - name: metrics
      port: 8000       # Port for exposing Prometheus metrics
      targetPort: 8000
  selector:
    app: python-guestbook
    tier: db
