apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-mongodb
  labels:
    app: python-guestbook
    tier: db
    monitoring: "enabled"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
    # - name: metrics
    #   port: 9216
    #   targetPort: 9216
  selector:
    app: python-guestbook
    tier: db
