apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app: {{ .Values.appName }}
    tier: db
    monitoring: "enabled"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.mongo.metricsPort }}"
spec:
  ports:
    - name: http-server
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
    - name: metrics
      port: {{ .Values.mongo.metricsPort }}
      targetPort: {{ .Values.mongo.metricsPort }}
  selector:
    app: {{ .Values.appName }}
    tier: db
