################################################################################
# WARNING: This MongoDB deployment is not suitable for production as the data is
# not persistently stored and will go away every time the Pod restarts. Consider
# using a Helm chart that provisions a StatefulSet instead of Deployment.
################################################################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app: {{ .Values.appName }}
    tier: db
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: db
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: db
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
          - name: http-server
            containerPort: {{ .Values.mongo.service.port }}
          env:
          - name: PORT
            value: "{{ .Values.mongo.service.port }}"
          - name: GUESTBOOK_DB_ADDR
            value: "{{ .Values.mongo.name }}:{{ .Values.mongo.service.port }}"
          - name: MONGO_DB_URI
            value: "mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@{{ .Values.mongo.name }}:{{ .Values.mongo.service.port }}"
