apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: {{ .Values.namespace | default "monitoring" }}
type: Opaque
data:
  PAGERDUTY_SERVICE_KEY: {{ .Values.pagerduty.serviceKey | b64enc | quote }}
