apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.serviceType }} # Updated to match frontend service type
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "guestbook.selectorLabels" . | nindent 4 }}
