apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-guestbook-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: python-guestbook
  endpoints:
    # Frontend metrics (Flask app exposing metrics on port 8000)
    - port: metrics
      interval: 30s
      path: /metrics
      targetPort: 8000    # Frontend port for metrics
    # Backend metrics (Updated to use 8001 for backend metrics)
    - port: http
      interval: 30s
      path: /metrics
      targetPort: 8000    # Corrected backend port for metrics
    # MongoDB metrics (MongoDB exporter exposes metrics on port 9216)
    - port: metrics
      interval: 30s
      path: /metrics
      targetPort: 9216    # MongoDB exporter port for metrics
  namespaceSelector:
    any: true
