apiVersion: v1
kind: Service
metadata:
  name: python-guestbook-backend
  labels:
    app: python-guestbook
    tier: backend
    monitoring: "enabled"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"  # Update to new metrics port
spec:
  type: ClusterIP
  selector:
    app: python-guestbook
    tier: backend
  ports:
    - name: http-server
      port: 8080       # Port for backend API
      targetPort: 8080 # Target port for backend API
    - name: metrics
      port: 8000       # Port for exposing Prometheus metrics
      targetPort: 8000 # Target port for Prometheus metrics