monitoring:
  prometheus:
    enabled: true
    namespace: monitoring  # Ensuring Prometheus is deployed in the monitoring namespace

    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        route:
          receiver: "pagerduty"
          group_by: ["namespace"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
        receivers:
          - name: "pagerduty"
            pagerduty_configs:
              - service_key: "2439d0f35b834908c19743e7449959a5"  # Replace with actual key
                severity: "critical"
                send_resolved: true
        inhibit_rules:
          - source_match:
              severity: "critical"
            target_match:
              severity: "warning"
            equal: ["alertname", "namespace", "instance"]
          - source_match:
              severity: "warning"
            target_match:
              severity: "info"
            equal: ["alertname", "namespace"]

    server:
      persistentVolume:
        enabled: true
        size: 8Gi

    grafana:
      enabled: true
      adminPassword: "yourpassword"

    serviceMonitor:
      enabled: true
      selector:
        matchLabels:
          app: python-guestbook
      endpoints:
        - port: metrics
          interval: 30s
          path: /metrics
          targetPort: 8000
      namespaceSelector:
        any: true

    # **Adding Rules for Alerts**
    additionalPrometheusRules:
      enabled: true
      rules:
        - alert: HighCPUUsage
          expr: avg(rate(container_cpu_usage_seconds_total[5m])) > 0.8
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Container CPU usage is above 80% for 2 minutes."

        - alert: HighMemoryUsage
          expr: avg(container_memory_usage_bytes) > 500000000
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High Memory Usage"
            description: "Memory usage exceeded 500MB for 5 minutes."
